// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.mzm.poker.protobuf.test;

public final class MsgOuterClass {
  private MsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool a = 1;</code>
     */
    boolean getA();

    /**
     * <code>optional int32 b = 2;</code>
     */
    int getB();

    /**
     * <code>optional int64 c = 3;</code>
     */
    long getC();

    /**
     * <code>optional float d = 4;</code>
     */
    float getD();

    /**
     * <code>optional double e = 5;</code>
     */
    double getE();

    /**
     * <code>optional string f = 6;</code>
     */
    java.lang.String getF();
    /**
     * <code>optional string f = 6;</code>
     */
    com.google.protobuf.ByteString
        getFBytes();
  }
  /**
   * Protobuf type {@code Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Msg)
      MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Msg() {
      a_ = false;
      b_ = 0;
      c_ = 0L;
      d_ = 0F;
      e_ = 0D;
      f_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              a_ = input.readBool();
              break;
            }
            case 16: {

              b_ = input.readInt32();
              break;
            }
            case 24: {

              c_ = input.readInt64();
              break;
            }
            case 37: {

              d_ = input.readFloat();
              break;
            }
            case 41: {

              e_ = input.readDouble();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();

              f_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mzm.poker.protobuf.test.MsgOuterClass.internal_static_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mzm.poker.protobuf.test.MsgOuterClass.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mzm.poker.protobuf.test.MsgOuterClass.Msg.class, com.mzm.poker.protobuf.test.MsgOuterClass.Msg.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private boolean a_;
    /**
     * <code>optional bool a = 1;</code>
     */
    public boolean getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private int b_;
    /**
     * <code>optional int32 b = 2;</code>
     */
    public int getB() {
      return b_;
    }

    public static final int C_FIELD_NUMBER = 3;
    private long c_;
    /**
     * <code>optional int64 c = 3;</code>
     */
    public long getC() {
      return c_;
    }

    public static final int D_FIELD_NUMBER = 4;
    private float d_;
    /**
     * <code>optional float d = 4;</code>
     */
    public float getD() {
      return d_;
    }

    public static final int E_FIELD_NUMBER = 5;
    private double e_;
    /**
     * <code>optional double e = 5;</code>
     */
    public double getE() {
      return e_;
    }

    public static final int F_FIELD_NUMBER = 6;
    private volatile java.lang.Object f_;
    /**
     * <code>optional string f = 6;</code>
     */
    public java.lang.String getF() {
      java.lang.Object ref = f_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          f_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string f = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFBytes() {
      java.lang.Object ref = f_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        f_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != false) {
        output.writeBool(1, a_);
      }
      if (b_ != 0) {
        output.writeInt32(2, b_);
      }
      if (c_ != 0L) {
        output.writeInt64(3, c_);
      }
      if (d_ != 0F) {
        output.writeFloat(4, d_);
      }
      if (e_ != 0D) {
        output.writeDouble(5, e_);
      }
      if (!getFBytes().isEmpty()) {
        output.writeBytes(6, getFBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, a_);
      }
      if (b_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, b_);
      }
      if (c_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, c_);
      }
      if (d_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, d_);
      }
      if (e_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, e_);
      }
      if (!getFBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getFBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mzm.poker.protobuf.test.MsgOuterClass.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg)
        com.mzm.poker.protobuf.test.MsgOuterClass.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mzm.poker.protobuf.test.MsgOuterClass.internal_static_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mzm.poker.protobuf.test.MsgOuterClass.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mzm.poker.protobuf.test.MsgOuterClass.Msg.class, com.mzm.poker.protobuf.test.MsgOuterClass.Msg.Builder.class);
      }

      // Construct using com.mzm.poker.protobuf.test.MsgOuterClass.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a_ = false;

        b_ = 0;

        c_ = 0L;

        d_ = 0F;

        e_ = 0D;

        f_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mzm.poker.protobuf.test.MsgOuterClass.internal_static_Msg_descriptor;
      }

      public com.mzm.poker.protobuf.test.MsgOuterClass.Msg getDefaultInstanceForType() {
        return com.mzm.poker.protobuf.test.MsgOuterClass.Msg.getDefaultInstance();
      }

      public com.mzm.poker.protobuf.test.MsgOuterClass.Msg build() {
        com.mzm.poker.protobuf.test.MsgOuterClass.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mzm.poker.protobuf.test.MsgOuterClass.Msg buildPartial() {
        com.mzm.poker.protobuf.test.MsgOuterClass.Msg result = new com.mzm.poker.protobuf.test.MsgOuterClass.Msg(this);
        result.a_ = a_;
        result.b_ = b_;
        result.c_ = c_;
        result.d_ = d_;
        result.e_ = e_;
        result.f_ = f_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mzm.poker.protobuf.test.MsgOuterClass.Msg) {
          return mergeFrom((com.mzm.poker.protobuf.test.MsgOuterClass.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mzm.poker.protobuf.test.MsgOuterClass.Msg other) {
        if (other == com.mzm.poker.protobuf.test.MsgOuterClass.Msg.getDefaultInstance()) return this;
        if (other.getA() != false) {
          setA(other.getA());
        }
        if (other.getB() != 0) {
          setB(other.getB());
        }
        if (other.getC() != 0L) {
          setC(other.getC());
        }
        if (other.getD() != 0F) {
          setD(other.getD());
        }
        if (other.getE() != 0D) {
          setE(other.getE());
        }
        if (!other.getF().isEmpty()) {
          f_ = other.f_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mzm.poker.protobuf.test.MsgOuterClass.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mzm.poker.protobuf.test.MsgOuterClass.Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean a_ ;
      /**
       * <code>optional bool a = 1;</code>
       */
      public boolean getA() {
        return a_;
      }
      /**
       * <code>optional bool a = 1;</code>
       */
      public Builder setA(boolean value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool a = 1;</code>
       */
      public Builder clearA() {
        
        a_ = false;
        onChanged();
        return this;
      }

      private int b_ ;
      /**
       * <code>optional int32 b = 2;</code>
       */
      public int getB() {
        return b_;
      }
      /**
       * <code>optional int32 b = 2;</code>
       */
      public Builder setB(int value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 b = 2;</code>
       */
      public Builder clearB() {
        
        b_ = 0;
        onChanged();
        return this;
      }

      private long c_ ;
      /**
       * <code>optional int64 c = 3;</code>
       */
      public long getC() {
        return c_;
      }
      /**
       * <code>optional int64 c = 3;</code>
       */
      public Builder setC(long value) {
        
        c_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 c = 3;</code>
       */
      public Builder clearC() {
        
        c_ = 0L;
        onChanged();
        return this;
      }

      private float d_ ;
      /**
       * <code>optional float d = 4;</code>
       */
      public float getD() {
        return d_;
      }
      /**
       * <code>optional float d = 4;</code>
       */
      public Builder setD(float value) {
        
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float d = 4;</code>
       */
      public Builder clearD() {
        
        d_ = 0F;
        onChanged();
        return this;
      }

      private double e_ ;
      /**
       * <code>optional double e = 5;</code>
       */
      public double getE() {
        return e_;
      }
      /**
       * <code>optional double e = 5;</code>
       */
      public Builder setE(double value) {
        
        e_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double e = 5;</code>
       */
      public Builder clearE() {
        
        e_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object f_ = "";
      /**
       * <code>optional string f = 6;</code>
       */
      public java.lang.String getF() {
        java.lang.Object ref = f_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            f_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string f = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFBytes() {
        java.lang.Object ref = f_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          f_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string f = 6;</code>
       */
      public Builder setF(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string f = 6;</code>
       */
      public Builder clearF() {
        
        f_ = getDefaultInstance().getF();
        onChanged();
        return this;
      }
      /**
       * <code>optional string f = 6;</code>
       */
      public Builder setFBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        f_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Msg)
    }

    // @@protoc_insertion_point(class_scope:Msg)
    private static final com.mzm.poker.protobuf.test.MsgOuterClass.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mzm.poker.protobuf.test.MsgOuterClass.Msg();
    }

    public static com.mzm.poker.protobuf.test.MsgOuterClass.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<Msg> PARSER =
        new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Msg(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    public com.mzm.poker.protobuf.test.MsgOuterClass.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\"G\n\003Msg\022\t\n\001a\030\001 \001(\010\022\t\n\001b\030\002 \001(\005" +
      "\022\t\n\001c\030\003 \001(\003\022\t\n\001d\030\004 \001(\002\022\t\n\001e\030\005 \001(\001\022\t\n\001f\030\006" +
      " \001(\tB\035\n\033com.mzm.poker.protobuf.testb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Msg_descriptor,
        new java.lang.String[] { "A", "B", "C", "D", "E", "F", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
