// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.mzm.poker.protobuf.test;

public final class Protocal {
  private Protocal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mzm.poker.protobuf.test.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 length = 1;</code>
     */
    int getLength();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 autoNum = 2;</code>
     */
    int getAutoNum();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 checksum = 3;</code>
     */
    int getChecksum();

    /**
     * <pre>
     *MsgType|encrypt
     * </pre>
     *
     * <code>optional int32 msgType = 4;</code>
     */
    int getMsgType();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional bytes body = 5;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code com.mzm.poker.protobuf.test.Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mzm.poker.protobuf.test.Msg)
      MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      length_ = 0;
      autoNum_ = 0;
      checksum_ = 0;
      msgType_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              length_ = input.readInt32();
              break;
            }
            case 16: {

              autoNum_ = input.readInt32();
              break;
            }
            case 24: {

              checksum_ = input.readInt32();
              break;
            }
            case 32: {

              msgType_ = input.readInt32();
              break;
            }
            case 42: {

              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mzm.poker.protobuf.test.Protocal.Msg.class, com.mzm.poker.protobuf.test.Protocal.Msg.Builder.class);
    }

    public static final int LENGTH_FIELD_NUMBER = 1;
    private int length_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 length = 1;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int AUTONUM_FIELD_NUMBER = 2;
    private int autoNum_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 autoNum = 2;</code>
     */
    public int getAutoNum() {
      return autoNum_;
    }

    public static final int CHECKSUM_FIELD_NUMBER = 3;
    private int checksum_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 checksum = 3;</code>
     */
    public int getChecksum() {
      return checksum_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 4;
    private int msgType_;
    /**
     * <pre>
     *MsgType|encrypt
     * </pre>
     *
     * <code>optional int32 msgType = 4;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional bytes body = 5;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (length_ != 0) {
        output.writeInt32(1, length_);
      }
      if (autoNum_ != 0) {
        output.writeInt32(2, autoNum_);
      }
      if (checksum_ != 0) {
        output.writeInt32(3, checksum_);
      }
      if (msgType_ != 0) {
        output.writeInt32(4, msgType_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(5, body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, length_);
      }
      if (autoNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, autoNum_);
      }
      if (checksum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, checksum_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, msgType_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, body_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mzm.poker.protobuf.test.Protocal.Msg)) {
        return super.equals(obj);
      }
      com.mzm.poker.protobuf.test.Protocal.Msg other = (com.mzm.poker.protobuf.test.Protocal.Msg) obj;

      boolean result = true;
      result = result && (getLength()
          == other.getLength());
      result = result && (getAutoNum()
          == other.getAutoNum());
      result = result && (getChecksum()
          == other.getChecksum());
      result = result && (getMsgType()
          == other.getMsgType());
      result = result && getBody()
          .equals(other.getBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (37 * hash) + AUTONUM_FIELD_NUMBER;
      hash = (53 * hash) + getAutoNum();
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getChecksum();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mzm.poker.protobuf.test.Protocal.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mzm.poker.protobuf.test.Protocal.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mzm.poker.protobuf.test.Protocal.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mzm.poker.protobuf.test.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mzm.poker.protobuf.test.Msg)
        com.mzm.poker.protobuf.test.Protocal.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mzm.poker.protobuf.test.Protocal.Msg.class, com.mzm.poker.protobuf.test.Protocal.Msg.Builder.class);
      }

      // Construct using com.mzm.poker.protobuf.test.Protocal.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        length_ = 0;

        autoNum_ = 0;

        checksum_ = 0;

        msgType_ = 0;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_Msg_descriptor;
      }

      public com.mzm.poker.protobuf.test.Protocal.Msg getDefaultInstanceForType() {
        return com.mzm.poker.protobuf.test.Protocal.Msg.getDefaultInstance();
      }

      public com.mzm.poker.protobuf.test.Protocal.Msg build() {
        com.mzm.poker.protobuf.test.Protocal.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mzm.poker.protobuf.test.Protocal.Msg buildPartial() {
        com.mzm.poker.protobuf.test.Protocal.Msg result = new com.mzm.poker.protobuf.test.Protocal.Msg(this);
        result.length_ = length_;
        result.autoNum_ = autoNum_;
        result.checksum_ = checksum_;
        result.msgType_ = msgType_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mzm.poker.protobuf.test.Protocal.Msg) {
          return mergeFrom((com.mzm.poker.protobuf.test.Protocal.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mzm.poker.protobuf.test.Protocal.Msg other) {
        if (other == com.mzm.poker.protobuf.test.Protocal.Msg.getDefaultInstance()) return this;
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        if (other.getAutoNum() != 0) {
          setAutoNum(other.getAutoNum());
        }
        if (other.getChecksum() != 0) {
          setChecksum(other.getChecksum());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mzm.poker.protobuf.test.Protocal.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mzm.poker.protobuf.test.Protocal.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int length_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public Builder setLength(int value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public Builder clearLength() {
        
        length_ = 0;
        onChanged();
        return this;
      }

      private int autoNum_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 autoNum = 2;</code>
       */
      public int getAutoNum() {
        return autoNum_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 autoNum = 2;</code>
       */
      public Builder setAutoNum(int value) {
        
        autoNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 autoNum = 2;</code>
       */
      public Builder clearAutoNum() {
        
        autoNum_ = 0;
        onChanged();
        return this;
      }

      private int checksum_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 checksum = 3;</code>
       */
      public int getChecksum() {
        return checksum_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 checksum = 3;</code>
       */
      public Builder setChecksum(int value) {
        
        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 checksum = 3;</code>
       */
      public Builder clearChecksum() {
        
        checksum_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       *MsgType|encrypt
       * </pre>
       *
       * <code>optional int32 msgType = 4;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       *MsgType|encrypt
       * </pre>
       *
       * <code>optional int32 msgType = 4;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *MsgType|encrypt
       * </pre>
       *
       * <code>optional int32 msgType = 4;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes body = 5;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes body = 5;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes body = 5;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.mzm.poker.protobuf.test.Msg)
    }

    // @@protoc_insertion_point(class_scope:com.mzm.poker.protobuf.test.Msg)
    private static final com.mzm.poker.protobuf.test.Protocal.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mzm.poker.protobuf.test.Protocal.Msg();
    }

    public static com.mzm.poker.protobuf.test.Protocal.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    public com.mzm.poker.protobuf.test.Protocal.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface rpcMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mzm.poker.protobuf.test.rpcMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 length = 1;</code>
     */
    int getLength();

    /**
     * <pre>
     *MsgType|encrypt
     * </pre>
     *
     * <code>optional int32 msgType = 2;</code>
     */
    int getMsgType();

    /**
     * <code>optional int64 roleId = 3;</code>
     */
    long getRoleId();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional bytes body = 5;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code com.mzm.poker.protobuf.test.rpcMsg}
   */
  public  static final class rpcMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mzm.poker.protobuf.test.rpcMsg)
      rpcMsgOrBuilder {
    // Use rpcMsg.newBuilder() to construct.
    private rpcMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private rpcMsg() {
      length_ = 0;
      msgType_ = 0;
      roleId_ = 0L;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private rpcMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              length_ = input.readInt32();
              break;
            }
            case 16: {

              msgType_ = input.readInt32();
              break;
            }
            case 24: {

              roleId_ = input.readInt64();
              break;
            }
            case 42: {

              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_rpcMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_rpcMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mzm.poker.protobuf.test.Protocal.rpcMsg.class, com.mzm.poker.protobuf.test.Protocal.rpcMsg.Builder.class);
    }

    public static final int LENGTH_FIELD_NUMBER = 1;
    private int length_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional int32 length = 1;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <pre>
     *MsgType|encrypt
     * </pre>
     *
     * <code>optional int32 msgType = 2;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int ROLEID_FIELD_NUMBER = 3;
    private long roleId_;
    /**
     * <code>optional int64 roleId = 3;</code>
     */
    public long getRoleId() {
      return roleId_;
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     * </pre>
     *
     * <code>optional bytes body = 5;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (length_ != 0) {
        output.writeInt32(1, length_);
      }
      if (msgType_ != 0) {
        output.writeInt32(2, msgType_);
      }
      if (roleId_ != 0L) {
        output.writeInt64(3, roleId_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(5, body_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, length_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgType_);
      }
      if (roleId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, roleId_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, body_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mzm.poker.protobuf.test.Protocal.rpcMsg)) {
        return super.equals(obj);
      }
      com.mzm.poker.protobuf.test.Protocal.rpcMsg other = (com.mzm.poker.protobuf.test.Protocal.rpcMsg) obj;

      boolean result = true;
      result = result && (getLength()
          == other.getLength());
      result = result && (getMsgType()
          == other.getMsgType());
      result = result && (getRoleId()
          == other.getRoleId());
      result = result && getBody()
          .equals(other.getBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + ROLEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoleId());
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mzm.poker.protobuf.test.Protocal.rpcMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mzm.poker.protobuf.test.rpcMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mzm.poker.protobuf.test.rpcMsg)
        com.mzm.poker.protobuf.test.Protocal.rpcMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_rpcMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_rpcMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mzm.poker.protobuf.test.Protocal.rpcMsg.class, com.mzm.poker.protobuf.test.Protocal.rpcMsg.Builder.class);
      }

      // Construct using com.mzm.poker.protobuf.test.Protocal.rpcMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        length_ = 0;

        msgType_ = 0;

        roleId_ = 0L;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mzm.poker.protobuf.test.Protocal.internal_static_com_mzm_poker_protobuf_test_rpcMsg_descriptor;
      }

      public com.mzm.poker.protobuf.test.Protocal.rpcMsg getDefaultInstanceForType() {
        return com.mzm.poker.protobuf.test.Protocal.rpcMsg.getDefaultInstance();
      }

      public com.mzm.poker.protobuf.test.Protocal.rpcMsg build() {
        com.mzm.poker.protobuf.test.Protocal.rpcMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mzm.poker.protobuf.test.Protocal.rpcMsg buildPartial() {
        com.mzm.poker.protobuf.test.Protocal.rpcMsg result = new com.mzm.poker.protobuf.test.Protocal.rpcMsg(this);
        result.length_ = length_;
        result.msgType_ = msgType_;
        result.roleId_ = roleId_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mzm.poker.protobuf.test.Protocal.rpcMsg) {
          return mergeFrom((com.mzm.poker.protobuf.test.Protocal.rpcMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mzm.poker.protobuf.test.Protocal.rpcMsg other) {
        if (other == com.mzm.poker.protobuf.test.Protocal.rpcMsg.getDefaultInstance()) return this;
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getRoleId() != 0L) {
          setRoleId(other.getRoleId());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mzm.poker.protobuf.test.Protocal.rpcMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mzm.poker.protobuf.test.Protocal.rpcMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int length_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public Builder setLength(int value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional int32 length = 1;</code>
       */
      public Builder clearLength() {
        
        length_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       *MsgType|encrypt
       * </pre>
       *
       * <code>optional int32 msgType = 2;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       *MsgType|encrypt
       * </pre>
       *
       * <code>optional int32 msgType = 2;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *MsgType|encrypt
       * </pre>
       *
       * <code>optional int32 msgType = 2;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private long roleId_ ;
      /**
       * <code>optional int64 roleId = 3;</code>
       */
      public long getRoleId() {
        return roleId_;
      }
      /**
       * <code>optional int64 roleId = 3;</code>
       */
      public Builder setRoleId(long value) {
        
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 roleId = 3;</code>
       */
      public Builder clearRoleId() {
        
        roleId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes body = 5;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes body = 5;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>optional bytes body = 5;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.mzm.poker.protobuf.test.rpcMsg)
    }

    // @@protoc_insertion_point(class_scope:com.mzm.poker.protobuf.test.rpcMsg)
    private static final com.mzm.poker.protobuf.test.Protocal.rpcMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mzm.poker.protobuf.test.Protocal.rpcMsg();
    }

    public static com.mzm.poker.protobuf.test.Protocal.rpcMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<rpcMsg>
        PARSER = new com.google.protobuf.AbstractParser<rpcMsg>() {
      public rpcMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new rpcMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<rpcMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<rpcMsg> getParserForType() {
      return PARSER;
    }

    public com.mzm.poker.protobuf.test.Protocal.rpcMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzm_poker_protobuf_test_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzm_poker_protobuf_test_Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mzm_poker_protobuf_test_rpcMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mzm_poker_protobuf_test_rpcMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\033com.mzm.poker.protobuf.test" +
      "\"W\n\003Msg\022\016\n\006length\030\001 \001(\005\022\017\n\007autoNum\030\002 \001(\005" +
      "\022\020\n\010checksum\030\003 \001(\005\022\017\n\007msgType\030\004 \001(\005\022\014\n\004b" +
      "ody\030\005 \001(\014\"G\n\006rpcMsg\022\016\n\006length\030\001 \001(\005\022\017\n\007m" +
      "sgType\030\002 \001(\005\022\016\n\006roleId\030\003 \001(\003\022\014\n\004body\030\005 \001" +
      "(\014B\'\n\033com.mzm.poker.protobuf.testB\010Proto" +
      "calb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mzm_poker_protobuf_test_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mzm_poker_protobuf_test_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzm_poker_protobuf_test_Msg_descriptor,
        new java.lang.String[] { "Length", "AutoNum", "Checksum", "MsgType", "Body", });
    internal_static_com_mzm_poker_protobuf_test_rpcMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mzm_poker_protobuf_test_rpcMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mzm_poker_protobuf_test_rpcMsg_descriptor,
        new java.lang.String[] { "Length", "MsgType", "RoleId", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
